# FastAPI Configuration

api:
  title: "DocuInfo API"
  description: "Document Information Extraction API with Multimodal LLM"
  version: "1.0.0"
  host: ${API_HOST:0.0.0.0}
  port: ${API_PORT:8001}

# CORS Settings
cors:
  allow_origins:
    - "http://localhost:3001"
    - "http://localhost:5173"
    - "http://127.0.0.1:3001"
    - "http://127.0.0.1:5173"
  allow_credentials: true
  allow_methods:
    - "*"
  allow_headers:
    - "*"

# File Upload Settings
upload:
  max_size_mb: 500
  allowed_extensions:
    - .pdf
    - .doc
    - .docx
    - .txt
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
    - .tiff
  temp_dir: "storage/temp"

# Rate Limiting (future)
rate_limit:
  enabled: false
  requests_per_minute: 10
